# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thomas/rendu3/cpp_rtype

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thomas/rendu3/cpp_rtype

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/rendu3/cpp_rtype/CMakeFiles /home/thomas/rendu3/cpp_rtype/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/rendu3/cpp_rtype/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r-type-client

# Build rule for target.
r-type-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 r-type-client
.PHONY : r-type-client

# fast build rule for target.
r-type-client/fast:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/build
.PHONY : r-type-client/fast

#=============================================================================
# Target rules for targets named r-type

# Build rule for target.
r-type: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 r-type
.PHONY : r-type

# fast build rule for target.
r-type/fast:
	$(MAKE) -f CMakeFiles/r-type.dir/build.make CMakeFiles/r-type.dir/build
.PHONY : r-type/fast

#=============================================================================
# Target rules for targets named r-type-server

# Build rule for target.
r-type-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 r-type-server
.PHONY : r-type-server

# fast build rule for target.
r-type-server/fast:
	$(MAKE) -f CMakeFiles/r-type-server.dir/build.make CMakeFiles/r-type-server.dir/build
.PHONY : r-type-server/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/r-type.dir/build.make CMakeFiles/r-type.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/r-type.dir/build.make CMakeFiles/r-type.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/r-type.dir/build.make CMakeFiles/r-type.dir/main.cpp.s
.PHONY : main.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/gameEngine/Mathematics.o: src/gameEngine/Mathematics.cpp.o

.PHONY : src/gameEngine/Mathematics.o

# target to build an object file
src/gameEngine/Mathematics.cpp.o:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Mathematics.cpp.o
.PHONY : src/gameEngine/Mathematics.cpp.o

src/gameEngine/Mathematics.i: src/gameEngine/Mathematics.cpp.i

.PHONY : src/gameEngine/Mathematics.i

# target to preprocess a source file
src/gameEngine/Mathematics.cpp.i:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Mathematics.cpp.i
.PHONY : src/gameEngine/Mathematics.cpp.i

src/gameEngine/Mathematics.s: src/gameEngine/Mathematics.cpp.s

.PHONY : src/gameEngine/Mathematics.s

# target to generate assembly for a file
src/gameEngine/Mathematics.cpp.s:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Mathematics.cpp.s
.PHONY : src/gameEngine/Mathematics.cpp.s

src/gameEngine/Physic.o: src/gameEngine/Physic.cpp.o

.PHONY : src/gameEngine/Physic.o

# target to build an object file
src/gameEngine/Physic.cpp.o:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Physic.cpp.o
.PHONY : src/gameEngine/Physic.cpp.o

src/gameEngine/Physic.i: src/gameEngine/Physic.cpp.i

.PHONY : src/gameEngine/Physic.i

# target to preprocess a source file
src/gameEngine/Physic.cpp.i:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Physic.cpp.i
.PHONY : src/gameEngine/Physic.cpp.i

src/gameEngine/Physic.s: src/gameEngine/Physic.cpp.s

.PHONY : src/gameEngine/Physic.s

# target to generate assembly for a file
src/gameEngine/Physic.cpp.s:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Physic.cpp.s
.PHONY : src/gameEngine/Physic.cpp.s

src/gameEngine/Position2D.o: src/gameEngine/Position2D.cpp.o

.PHONY : src/gameEngine/Position2D.o

# target to build an object file
src/gameEngine/Position2D.cpp.o:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Position2D.cpp.o
.PHONY : src/gameEngine/Position2D.cpp.o

src/gameEngine/Position2D.i: src/gameEngine/Position2D.cpp.i

.PHONY : src/gameEngine/Position2D.i

# target to preprocess a source file
src/gameEngine/Position2D.cpp.i:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Position2D.cpp.i
.PHONY : src/gameEngine/Position2D.cpp.i

src/gameEngine/Position2D.s: src/gameEngine/Position2D.cpp.s

.PHONY : src/gameEngine/Position2D.s

# target to generate assembly for a file
src/gameEngine/Position2D.cpp.s:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Position2D.cpp.s
.PHONY : src/gameEngine/Position2D.cpp.s

src/gameEngine/Rectangle.o: src/gameEngine/Rectangle.cpp.o

.PHONY : src/gameEngine/Rectangle.o

# target to build an object file
src/gameEngine/Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Rectangle.cpp.o
.PHONY : src/gameEngine/Rectangle.cpp.o

src/gameEngine/Rectangle.i: src/gameEngine/Rectangle.cpp.i

.PHONY : src/gameEngine/Rectangle.i

# target to preprocess a source file
src/gameEngine/Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Rectangle.cpp.i
.PHONY : src/gameEngine/Rectangle.cpp.i

src/gameEngine/Rectangle.s: src/gameEngine/Rectangle.cpp.s

.PHONY : src/gameEngine/Rectangle.s

# target to generate assembly for a file
src/gameEngine/Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/r-type-client.dir/build.make CMakeFiles/r-type-client.dir/src/gameEngine/Rectangle.cpp.s
.PHONY : src/gameEngine/Rectangle.cpp.s

src/server/main.o: src/server/main.cpp.o

.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) -f CMakeFiles/r-type-server.dir/build.make CMakeFiles/r-type-server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i

.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) -f CMakeFiles/r-type-server.dir/build.make CMakeFiles/r-type-server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s

.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) -f CMakeFiles/r-type-server.dir/build.make CMakeFiles/r-type-server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... r-type-client"
	@echo "... rebuild_cache"
	@echo "... r-type"
	@echo "... r-type-server"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/gameEngine/Mathematics.o"
	@echo "... src/gameEngine/Mathematics.i"
	@echo "... src/gameEngine/Mathematics.s"
	@echo "... src/gameEngine/Physic.o"
	@echo "... src/gameEngine/Physic.i"
	@echo "... src/gameEngine/Physic.s"
	@echo "... src/gameEngine/Position2D.o"
	@echo "... src/gameEngine/Position2D.i"
	@echo "... src/gameEngine/Position2D.s"
	@echo "... src/gameEngine/Rectangle.o"
	@echo "... src/gameEngine/Rectangle.i"
	@echo "... src/gameEngine/Rectangle.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

